### ISSUE TITLE
Issue with building_all.sh

### ISSUE THREAD

**Issue by neteng1** [poseidonos/poseidonos-gui#82]
Hello, I am trying to evaluate poseidonos. I installed and have running, poseidonos and was attempting to get poseidonos-gui up for management. I was following the instructions on the main page. Here are the issues I saw:

1.   The build_all.sh script failed because of missing npm application. 
      - I installed it manually with dependancies 
2.  Then when I ran it I got this:
      -------------------------------------------------
keith@POS-Log4:~/dev/ibosfos/poseidonos-gui/script$ sudo ./build_all.sh 
loadDep:socket.io-client  ▄ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN deprecated i18next-xhr-backend@3.2.2: replaced by i18next-http-backend
npm ERR! Linux 5.4.0-132-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/keith/dev/ibosfos/poseidonos-gui/src/mtool/ui/npm-debug.log

> ibof-frontend@0.2.92-10-gee4b776b build /home/keith/dev/ibosfos/poseidonos-gui/src/mtool/ui
> react-scripts build

sh: 1: react-scripts: not found

npm ERR! Linux 5.4.0-132-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ibof-frontend@0.2.92-10-gee4b776b build: `react-scripts build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ibof-frontend@0.2.92-10-gee4b776b build script 'react-scripts build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ibof-frontend package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ibof-frontend
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ibof-frontend
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/keith/dev/ibosfos/poseidonos-gui/src/mtool/ui/npm-debug.log
cp: cannot stat 'build/*': No such file or directory
keith@POS-Log4:~/dev/ibosfos/poseidonos-gui/script$
--------------------------------------------------------------------------------------
Am I missing a step? Any assistance you can lend me would be greatly appreciated.

**Comment by neteng1** [comment]
Okay, we figured out the issue here. I had nodejs running, but it was version 8.10. We upgraded to 14.21 and now It installs and I am able to get the GUI functioning.
